### PR TITLE
dependatool: Add NPM support

### PR DESCRIPTION
**Pull request by phlax**

### CODE REVIEW

**Comment by phlax** [comment]
@mmorel-35 im in 2 minds about this - if we are moving to renovate i think its probably obsolete

**Comment by mmorel-35** [comment]
If renovate is doing the Job it is indeed going to be useless.
But in the meanwhile you can activate it if you know that there won't be any bad impact on your existing code ?

**Comment by phlax** [comment]
>  But in the meanwhile you can activate it if you know that there won't be any bad impact on your existing code ?

probably a good idea - it at least needs a bit of deployment testing

**Comment by phlax** [comment]
i tested this locally and seems to work - we can add proper tests if we decide to keep for some reason

**Pull request merged**
