### PR TITLE
Generate dependabot configuration 

### PR DESCRIPTION
**Pull request by mmorel-35**
I have created a Makefile that is able to generate the dependabot config file with
```
make generate/dependabot
```

It generate a github-actions config for every action.yml that has uses actions (has "uses:" in it’s content)

It generate an npm config for every non empty package.json 

It generate a pip config for every non empty requirements.txt 

I’m not entirely satisfied with the way GITHUB_ACTIONS_DIRS is constructed but it works. It’s chaining grep to get the list of action.yml that contains "uses:" then get their parent directories (dirnames) then removes action.yml from the generated list (grep -v) . Any simplification idea ?

If you just want the dependabot.yml I can also remove the Makefile 

Signed-off-by: Matthieu MOREL <matthieu.morel35@gmail.com>

### CODE REVIEW

**Comment by phlax** [comment]
@mmorel-35 i think this kinda duplicates the functionality here https://github.com/envoyproxy/toolshed/tree/main/dependatool/dependatool

could we perhaps add npm support there?

im happy to do it as im familiar with tooling/tests/etc

**Comment by phlax** [comment]
hmm - i think that will need some update anyhow - atm it doesnt check parent folders - ie it expects a config for every dependency

**Comment by phlax** [comment]
my other hesitation is that i would really rather not add a Makefile - this repo runs on pants and already has some bazel thrown in

Pants has much better python support amongst other reasons, which is why i added it rather than bazel - bazel is the projects default build system

**Comment by mmorel-35** [comment]
OK,
I’ll remove the Makefile.
It’s better to add it to dependatool.
Are you still interested by the update of the dependabot.yml or shall I just close the PR ?

**Comment by phlax** [comment]
not sure tbh re actions updates - these necessarily get updated at the last minute before release - altho not all actions are referenced are internal

probs its a good idea

**Review by phlax — APPROVED** [review]
lgtm, thaks @mmorel-35 

lets add these for now - we can iterate if we need to

**Pull request merged**
