### PR TITLE
`gh-actions/envoy/ios/post`: Add timeout handling and make more generic

### PR DESCRIPTION
**Pull request by phlax**

### CODE REVIEW

**Comment by phlax** [comment]
cc @abeyad - this should allows to add back the missing test, and also makes the timeout fun available to all of the runs

**Review by abeyad — APPROVED** [review]
Is 5m enough?  Maybe start out with 20m and see how long it normally takes then adjust accordingly?

**Comment by phlax** [comment]
> Is 5m enough? 

that is what then swift-async-await originally had here https://github.com/envoyproxy/envoy/blob/5c4b0d653626122096b7b1dd0713f2d24aaf093d/.github/workflows/mobile-ios_build.yml#L241-L257

i think the others, at least, return *much* faster so if anything would be inclined to make it a lot less but i think lets start with this

**Comment by phlax** [comment]
also worth mentioning this the default input - so we can override it envoy side for specific tests

**Review by abeyad — APPROVED** [review]

**Pull request merged**
